[package]
name = "crypto-crawler-ffi"
version = "1.7.0"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
crypto-crawler = "1.7.0"

[build-dependencies]
cbindgen = "0.16.0"

[profile.release]
lto = true
codegen-units = 1
